# Generated by Django 5.2.17 on 2026-10-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=24)),
                ('high', models.DecimalField(decimal_places=8, max_digits=24)),
                ('low', models.DecimalField(decimal_places=8, max_digits=24)),
                ('close', models.DecimalField(decimal_places=8, max_digits=24)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30)),
                ('value', models.DecimalField(decimal_places=8, max_digits=30)),
                ('is_final', models.BooleanField(default=False)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='market.asset')),
            ],
            options={
                'ordering': ['asset', 'date'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'date'), name='uniq_candle_asset_date')],
            },
        ),
    ]
