# Generated by Django 5.2.17 on 2026-10-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_dailycandle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('cron', 'Vercel Cron'), ('beat', 'Celery beat'), ('manual', '수동 실행'), ('backfill', '과거 데이터 백필')], max_length=10)),
                ('status', models.CharField(choices=[('running', '실행 중'), ('success', '성공'), ('partial', '일부 실패'), ('failed', '실패')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('assets_count', models.PositiveIntegerField(default=0)),
                ('upserted_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
