# Generated by Django 5.2.17 on 2026-10-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_collectionrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('missing', '결측일'), ('ohlc_invalid', 'OHLC 규칙 위반'), ('non_positive', '0 이하 가격'), ('zero_volume', '거래량 0'), ('spike', '급등락'), ('stale', '수집 지연')], max_length=20)),
                ('severity', models.CharField(choices=[('error', '오류'), ('warning', '경고')], max_length=10)),
                ('detail', models.JSONField(default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='market.asset')),
                ('detected_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='market.collectionrun')),
            ],
            options={
                'ordering': ['-date', 'asset'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'date', 'type'), name='uniq_issue')],
            },
        ),
    ]
