# Generated by Django 5.2.17 on 2026-10-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_seed_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrityissue',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
