# Generated by Django 5.2.17 on 2026-10-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_integrityissue_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycandle',
            options={'ordering': ['asset_id', 'date']},
        ),
        migrations.AlterModelOptions(
            name='integrityissue',
            options={'ordering': ['-date', 'asset_id']},
        ),
    ]
