# Generated by Django 5.2.17 on 2026-10-02 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0007_ordering_by_asset_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField()),
                ('params_hash', models.CharField(max_length=64)),
                ('data_version', models.CharField(max_length=40)),
                ('metrics', models.JSONField()),
                ('benchmark', models.JSONField()),
                ('equity_curve', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='market.asset')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('params_hash', 'data_version'), name='uniq_backtest')],
            },
        ),
    ]
